This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file ./manuscript.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file manuscript.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file manuscript.acr....done (6 lines written, 0 warnings).
Output written in manuscript.acr.
Transcript written in manuscript.alg.
